apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::728956037968:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16EKMUP357XUR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::728956037968:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-03T17:42:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3142"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9d8676ef-bf88-4117-9f86-c3f6ce583cda
