apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::728956037968:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::728956037968:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VIWNQDVU96I0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-29T20:42:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1992"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 14b7200b-4c0b-4139-9ff0-323faeeb37b3
